GITHUB_REVIEW_LOG_URI: ""
GITHUB_TOKEN: ""
COMMIT_PROJECT: ""
COMMIT_BRANCH: ""
COMMIT_AUTHOR: ""
COMMIT_MESSAGE: ""

CHATGLM_APIHOST: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
CHATGLM_APIKEYSECRET: ""

WEIXIN_APPID: ""
WEIXIN_SECRET: ""
WEIXIN_TOUSER: ""
WEIXIN_TEMPLATE_ID: ""
