GITHUB_REVIEW_LOG_URI: "https://github.com/Robin-Jason/OpenAI-Code-Review-log"

CHATGLM_APIHOST: "https://open.bigmodel.cn/api/paas/v4/chat/completions"
CHATGLM_APIKEYSECRET: "febc2789803a43b48ae4d02f7b8342d8.CTTTXZRtWv9QLoLo"

WEIXIN_APPID: "wx3d35fdd548da215b"
WEIXIN_SECRET: "fc94cb0b166c3fd22d5fe1aa79a0b2e8"
WEIXIN_TOUSER: "otG1425gcvEh_K15dm3IH9zfdHXY"
WEIXIN_TEMPLATE_ID: "xsVeAi29gg7bXGhcK5gVVA4La02I4um7yD7AsID3y9A"
